---

- name: Test ansible
  shell: sudo touch test_ansible

- name: Install Python-ceph
  yum: name=python-ceph state=present

- name: Delete old repo
  shell: rm -rf Tiramisu
  args:
    removes: Tiramisu/this_is_dev_branch

- name: Clone ceph source code
  shell: git clone --recursive https://github.com/Nyan-Cats/Tiramisu.git --branch develop

- name: Change own for repo
  shell: sudo chown -R ceph Tiramisu

- name: Change group for repo
  shell: sudo chgrp -R ceph Tiramisu

- name: Install dependencies
  shell: ./install-deps.sh
  args:
    chdir: Tiramisu

- name: Install autoconf-archive
  yum: name=autoconf-archive state=present

- name: Build autogen
  shell: ./autogen.sh
  args:
    chdir: Tiramisu/ 

- name: Build config
  shell: ./configure 
  args:
    chdir: Tiramisu

- name: Build make
  shell: sudo make -j4
  args:
    chdir: Tiramisu

- name: Install ceph
  shell: sudo make install
  args:
    chdir: Tiramisu

- name: Delete config folder
  shell: sudo rm -r /etc/ceph/
  args:
    removes: /etc/ceph/ceph.conf

- name: Create dir /etc/ceph/
  shell: sudo mkdir /etc/ceph/

- name: Copy ceph.conf
  shell: sudo cp Tiramisu/tira_conf/ceph.conf /etc/ceph/

- name: Change own to ceph /etc/ceph/
  shell: sudo chown -R ceph /etc/ceph/

- name: Change group to ceph /etc/ceph/
  shell: sudo chgrp -R ceph /etc/ceph/

- name: Remove old mon key
  shell: sudo rm /tmp/ceph.mon.keyring
  args:
    removes: /tmp/ceph.mon.keyring

- name: Create a keyring for your cluster and generate a monitor secret key.
  shell: ceph-authtool --create-keyring /tmp/ceph.mon.keyring --gen-key -n mon. --cap mon 'allow *'

- name: Create a keyring for your cluster and generate a mds secret key.
  shell: ceph-authtool /tmp/ceph.mon.keyring --gen-key \
           -n mds.hp1 \
           --cap mds 'allow *' \
           --cap osd 'allow *' \
           --cap mon 'allow rwx'

- name: Generate an administrator keyring, generate a client.admin user and add the user to the keyring.
  shell: ceph-authtool --create-keyring /etc/ceph/ceph.client.admin.keyring --gen-key -n client.admin --set-uid=0 --cap mon 'allow *' --cap osd 'allow *' --cap mds 'allow'

- name: Add the client.admin key to the ceph.mon.keyring.
  shell: ceph-authtool /tmp/ceph.mon.keyring --import-keyring /etc/ceph/ceph.client.admin.keyring

- name: Generate a monitor map using the hostname(s), host IP address(es) and the FSID. Save it as /tmp/monmap
  shell: monmaptool --create --add hp2 10.0.1.2 --fsid a0cb9dec-7772-4ae2-a980-b69b42ef22ee /tmp/monmap

#- name: Copy python-ceph local lib to lib
#  shell: sudo cp /usr/local/lib/python2.7/site-packages/ceph* /usr/lib/python2.7/site-packages/
#  shell: sudo cp /usr/local/lib/python2.7/site-packages/rados* /usr/lib/python2.7/site-packages/
